apiVersion: install.armadaproject.io/v1alpha1
kind: LookoutIngester
metadata:
  name: armada-lookout-ingester
  namespace: armada
spec:
  image:
    repository: gresearch/armada-lookout-ingester
    tag: latest
  applicationConfig:
    postgres:
      connection:
        host: postgres.data.svc.cluster.local
        port: 5432
        user: armada
        password: armada
        dbname: lookout
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
