apiVersion: install.armadaproject.io/v1alpha1
kind: SchedulerIngester
metadata:
  name: armada-scheduler-ingester
  namespace: armada
spec:
  replicas: 1
  image:
    repository: gresearch/armada-scheduler-ingester
    tag: latest
  applicationConfig:
    postgres:
      connection:
        host: postgres.data.svc.cluster.local
        port: 5432
        user: armada
        password: armada
        dbname: scheduler
        sslmode: disable
    pulsar:
      URL: pulsar://pulsar-broker.data.svc.cluster.local:6650
