# This adds namespace-scoped permissions for the operator in the armada namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: armada-operator-namespace-role
  namespace: armada
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: armada-operator-namespace-rolebinding
  namespace: armada
subjects:
- kind: ServiceAccount
  name: armada-operator-controller-manager
  namespace: armada-system
roleRef:
  kind: Role
  name: armada-operator-namespace-role
  apiGroup: rbac.authorization.k8s.io
