---
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: data
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: pulsar
    port: 6650
    targetPort: 6650
  selector:
    app: pulsar
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
      - name: pulsar
        image: apachepulsar/pulsar:3.3.2
        command:
        - sh
        - -c
        - |
          bin/apply-config-from-env.py conf/standalone.conf
          exec bin/pulsar standalone --no-functions-worker --no-stream-storage
        env:
        - name: PULSAR_MEM
          value: "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=256m"
        - name: PULSAR_GC
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=10"
        ports:
        - name: http
          containerPort: 8080
        - name: pulsar
          containerPort: 6650
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: pulsar-data
          mountPath: /pulsar/data
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: pulsar-data
        emptyDir: {}
